import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitHub Repo Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bg = `antialiased text-slate-300 bg-slate-900`;
  return (
    <html lang="en">
      <body className={`${inter.className} m-7 bg-gradient-to-r ${bg} `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
